export const films = [
  '28daysLater',
  '500DaysOfSummer',
  'IT',
  'arrival',
  'chariotsOfFire',
  'chungkingExpress',
  'hotFuzz',
  'interstellar',
  'liloAndStitch',
  'manOfSteel',
  'matrix',
  'minions',
  'pocahontas',
  'scarface',
  'screamVI',
  'teletubbies',
  'theIronGiant',
  'theMandalorian',
  'thePursuitOfHappiness',
  'whiplash',
]

export const rows = [
  {
    title: 'Films That Marmalade My Croissant',
    films: [
      'whiplash',
      'hotFuzz',
      'chungkingExpress',
      'liloAndStitch',
      'interstellar',
      'thePursuitOfHappiness',
      '500DaysOfSummer',
      'theMandalorian',
      'pocahontas',
      'chariotsOfFire',
      'IT',
      'matrix',
    ],
  },
  {
    title: 'Critically-acclaimed Films With a Strong Peruvian influence',
    films: [
      'IT',
      'screamVI',
      '28daysLater',
      'scarface',
      'theMandalorian',
      'arrival',
      'matrix',
      'theIronGiant',
      'thePursuitOfHappiness',
    ],
  },
  {
    title: 'Bear Heavy Films',
    films: [
      'chariotsOfFire',
      '500DaysOfSummer',
      'arrival',
      'matrix',
      'manOfSteel',
      'hotFuzz',
      'interstellar',
      'liloAndStitch',
      'chungkingExpress',
      'minions',
    ],
  },
  {
    title: 'Films That Pair Well With a Carrot Based Lunch',
    films: [
      'teletubbies',
      'liloAndStitch',
      'pocahontas',
      'theIronGiant',
      'minions',
      'thePursuitOfHappiness',
      'manOfSteel',
      'scarface',
      'screamVI',
      'theMandalorian',
      'matrix',
      'whiplash',
    ],
  },
]
